# Author: FSN
# Maintainers: FSN
# Copyright:   2021, FSN GPL v2 or later
# Data Cleaning
# =============================================
#Cleaning extradiciones database
extradiciones = extradiciones %>%
    mutate(delito = case_when(delito == "abuso_sexual_cometido_contra_persona_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_continuo_contra_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_continuo_de_una_persona_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_contra_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_contra_menores_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_contra_persona_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_contra_un_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_contra_unas_personas_menores_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_criminal_calificado_de_persona_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_de_menores"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_de_persona_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_de_un_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_de_una_menor"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_de_una_menor"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_de_una_persona_menor_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_de_unas_personas_menores_de_edad"~ "abuso_sexual_menores",
                                  delito == "abuso_sexual_infantil" ~ "abuso_sexual_menores",
                              delito == "abandonar_el_lugar_donde_ocurrio_un_accidente_que_implico_un_fallecimiento_homicidio" ~ "abandono_lugar_homicidio",
                              delito == "abandonar_el_lugar_donde_ocurrio_un_choque_automovilistico_que_resulto_en_muerte" ~ "abandono_lugar_homicidio",
                              delito == "agesiones_calificadas_con_un_vehiculo_y_abandonar_el_lugar" ~ "abandono_lugar_homicidio",
                              delito == "abandono_de_personas_menor_de_edad" ~ "abandono_personas",
                              delito == "abrir_fuego_en_una_vivienda" ~ "delito_con_arma_de_fuego",
                              delito == "abuso_a_persona_mayor" ~ "abuso_persona_mayor",
                              delito == "acoso_cibernetico" ~ "acoso",
                              delito == "acoso" ~ "acoso",
                              delito == "acoso_y_violencia_contra_una_pareja_actual_o_anterior" ~ "acoso",
                              delito == "acto_lacsivo_y_lujurioso_con_menor_de_edad" ~ "actos_lascivos_contra_menores",
                              delito == "acto_lascivo_con_una_persona_menor_de_edad" ~"actos_lascivos_contra_menores",
                              delito == "acto_lascivo_y_obsceno_mediante_la_fuerza"~ "actos_lascivos_contra_menores",
                              delito == "actos_lascivos_forzado_con_menor_de_catorce_anos" ~ "actos_lascivos_contra_menores",
                              delito == "actos_lasivos_forzados_con_una_persona_menor_de_14_años_de_edad" ~ "actos_lascivos_contra_menores",
                              delito == "actos_sexuales_ilicitos_contra_menor_de_edad" ~ "actos_lascivos_contra_menores",
                              delito == "agresion_a_mano_armada" ~"agresion",
                              delito == "agresion_sexual_contra_menor_de_edad" ~ "agresion_sexual_contra_menor",
                              delito == "agresion_sexual_contra_menor_de_edad_como_parte_de_un_patron_de_abuso_en_violacion"~"agresion_sexual_contra_menor",
                              delito == "agresion_sexual_infantil" ~ "agresion_sexual_contra_menor",
                              delito == "agresiones" ~ "agresion",
                              delito == "allanamiento_de_morada_a_casa_habitacion" ~ "allanamiento_de_morada",
                              delito == "allanamiento_de_morada_a_casa_habitacion_en_primer_grado" ~ "allanamiento_de_morada_calificado",
                              delito == "allanamiento_de:morada" ~ "allanamiento_de_morada",
                              delito == "allanamiento_de_morada_calificado" ~ "allanamiento_de_morada",
                              delito == "alteracion_o_encubrimiento_de_pruebas" ~ "alteracion_de_pruebas",
                              delito == "amenazas_aterradoras" ~ "amenazas",
                              delito == "amenazas_violentas" ~ "amenazas",
                              delito == "amenza_y_temor_contra_una_persona_menor" ~ "amenazas",
                              delito == "articulos_relacionados_con_armas_provenientes_de_los_estados_unidos" ~ "delito_con_arma_de_fuego",
                              delito == "asalto_calificado_lesiones_en_primer_grado" ~ "asalto",
                              delito == "asalto_con_instrumento_mortal" ~ "asalto",
                              delito == "asalto_sexual_a_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_a_menores_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado" ~ "asalto_sexual",
                              delito == "asalto_sexual_calificado_ de_una_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado_como_violacion" ~ "asalto_sexual",
                              delito == "asalto_sexual_calificado_con_menor_de_catorce_anos_de_edad_quien_es_al_menos_siete_anos_mas_joven_que_el_acusado" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado_con_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado_contra_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado_contra_persona_menor_de_catorce_anos" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado_contra_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado_de_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_calificado_de_una_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_cometido_con_un_menor_de_edada" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_contra_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_contra_persona_menor_de_edad_violacion_en_segundo_grado" ~ "violacion_menor_de_edad",
                              delito == "asalto_sexual_contra_una_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_contra_unas_personas_menores_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_criminal" ~ "asalto_sexual",
                              delito == "asalto_sexual_de_una_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_infantil" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_infantil_y_delitos_relacionados" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_penal" ~ "asalto_sexual",
                              delito == "asalto_sexual_penal_calificado" ~ "asalto_sexual",
                              delito == "asalto_sexual_penal_y_depredador_de_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_y_abuso_sexual_contra_una_persona_menor_de_edad" ~ "asalto_sexual_menor",
                              delito == "asalto_sexual_infantil" ~ "asalto_sexual_menor",
                              delito == "asociación_delictuosa" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_contra_la_salud" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para cometer_homicidio_y_secuestro" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_delitos_contra_la_salud" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_delitos_de_fraude" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_falsificacion" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_fraude" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_fraude_electronico_y_bancario" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_homicidio" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_homicidio_en_ayuda_de_la_delincuencia_organizada" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_lesiones_con_un_arma_peligrosa_eb_ayuda_de_la_delincuencia_organizada" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_secuestro" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_cometer_un_homicidio_por_contrato" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_contrabandear_armas_de_fuego" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_contrabandear_municiones" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_dirigir_o_participar_en_la_conduccion_de_los_asuntos_de_una_empresa_de_delincuencia_organizada_asociacion_delictuosa_sobre_delincuencia_organizada" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_distribuir_una_sustancia_controlada" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_fabricar_cocaina_y_mariguana" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_fomentar_e_inducir_indocumentados" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_involucrarse_en_la_trata_de_mujeres_y_jovencitas_con_fines_de_explotacion_sexual" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_lavado_de_dinero" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_lavar_las_ganancias_del_narcotrafico" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_participar_en_un_grupo_criminal_organizado" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_para_poseer_con_la_intencion_de_distribuir_marihuana" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_por_distribuir_y_poseer" ~ "asociacion_delictuosa",
                              delito == "asociacion_delictuosa_que_implica_secuestro" ~ "asociacion_delictuosa",
                              delito == "ataque_y_delito_con_arma_de_fuego" ~ "ataque",
                              delito == "cargos_relacionados" ~ "delito_con_arma_de_fuego",
                              delito == "cometer_un_acto_lascivo_o_lujurioso_contra_menor_de_catorce_anos" ~ "actos_lascivos_contra_menores",
                              delito == "cometer_un_acto_obseno_y_lascivo_contra_menor_de_edad" ~ "actos_lascivos_contra_menores",
                              delito == "conducta_sexual_con_menores_de_edad" ~ "conducta_sexual_con_menor",
                              delito == "conducta_sexual_con_una_menor_de_edad" ~ "conducta_sexual_con_menor",
                              delito == "copula_oral" ~ "copula_oral_forzada",
                              delito == "copula_oral_mediante_el_uso_de_la_fuerza" ~ "copula_oral_forzada",
                              delito == "dar_informacion_falsa_con_conocimiento_de_causa_a_un_prestamista" ~ "falsedad_de_declaracion",
                              delito == "decalaracion_falsa_ante_autoridad_judicial" ~ "falsedad_de_declaracion",
                              delito == "declaraciones_falsas_a_agentes_federales" ~ "falsedad_de_declaracion",
                              delito == "declaraciones_falsas_en_documentos_de_un_banco_asegurado_federalmente" ~ "falsedad_de_declaracion",
                              delito == "delicuencia_organizada" ~ "delincuencia_organizada",
                              delito == "delito_con_armas_de_fuego_homicidio" ~ "delito_con_arma_de_fuego",
                              delito == "delito_de_arma_de_fuego" ~"delito_con_arma_de_fuego",
                              delito == "delito_federal_de_narcotrafico_contra_la_salud" ~ "delito_contra_la_salud",
                              delito == "delito_por_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "delito_violento" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_de_abuso_sexual_cometidos_contra_una_persona_menor_de_edad" ~ "abuso_sexual_menores",
                              delito == "delitos_de_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_federales_contra_la_salud" ~ "delito_contra_la_salud",
                              delito == "delitos_federales_de_trafico_de_armas" ~ "trafico_de_armas",
                              delito == "armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_federales_relativos_a_la_declaracion_de_impuestos" ~ "delitos_fiscales",
                              delito == "delitos_por_arma_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_por_armas" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_por_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_relacionados" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_relacionados_con_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_relacionados_con_el_narcotrafico" ~ "delito_contra_la_salud",
                              delito == "delitos_relacionados_con_la_exportacion_ilegal_de_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_relacionados_con_robo" ~ "robo",
                              delito == "delitos_relacionados_con_secuestro" ~ "secuestro",
                              delito == "delitos_relacionados_en_materia_de_migracion" ~ "delitos_en_materia_migratoria",
                              delito == "delitos_relacionados_que_implican_a_menores_de_edad" ~ "delitos_cometidos_contra_menores",
                              delito == "delitos_sexuales_cometidos_con_un_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "delitos_sexuales_cometidos_contra_de_unas_personas_menores_de_edad" ~ "delito_sexual_menores",
                              delito == "delitos_sexuales_cometidos_contra_una_persona_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "delitos_sexuales_cometidos_contra_unas_personas_menores_de_edad" ~ "delito_sexual_menores",
                              delito == "delitos_sexuales_con_una_persona_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "delitos_sexuales_contra_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "delitos_sexuales_relacionados" ~ "delitos_sexuales",
                              delito == "descargo_criminal_de_arma_de_fuego_contra_vehiculo_ocupado" ~ "delito_con_arma_de_fuego",
                              delito == "descargo_de_una_arma_de_fuego_en_una_vivienda_habitada" ~ "delito_con_arma_de_fuego",
                              delito == "descargo_malicioso_de_arma_de_fuego_contra_vehiculo_con_personas" ~ "delito_con_arma_de_fuego",
                              delito == "disparar_contra_un_edificio_o_vehiculo_con_persona_adentro" ~ "delito_con_arma_de_fuego",
                              delito == "disparar_contra_un_vehiculo_con_pasajeros_abordo" ~ "delito_con_arma_de_fuego",
                              delito == "distribucion_de_las_ganancias_de_un_negocio_de_prostitucion" ~ "explotacion_sexual",
                              delito == "distribucion_de_un_material_que_implica_la_explotacion_sexual_de_una_menor_de_edad" ~ "pornografia_infantil",
                              delito == "distribucion_y_posesion_de_cocaina_contra_la_salud" ~ "delito_contra_la_salud",
                              delito == "encubrir_una_muerte_por_homicidio" ~ "homicidio",
                              delito == "entrada_penal_ilegal_a_la_propiedad_de_alguien" ~ "allanamiento_de_morada",
                              delito == "estrangulamiento" ~"homicidio",
                              delito == "exportacion_ilegal_de_municiones" ~ "trafico_de_armas",
                              delito == "exportar_mercancia" ~ "exportacion_ilegal",
                              delito == "falsificacion_de_documentos" ~ "falsificacion",
                              delito == "filacion_a_una_pandilla" ~ "asociacion_delictuosa",
                              delito == "fraude_bancario" ~ "fraude",
                              delito == "fraude_cibernetico" ~"fraude",
                              delito == "fraude_electronico" ~ "fraude",
                              delito == "fraude_postal" ~ "fraude",
                              delito == "grave_delito_de_robo" ~ "robo",
                              delito == "haber_hecho_una_afirmacion_falsa_de_cuidadana_estadounidense" ~ "falsificacion",
                              delito == "hacer_y_poseer_pornografia_infantil" ~ "pornografia_infantil",
                              delito == "heridas_corporales_a_su_conyuge" ~ "lesiones",
                              delito == "homicidio_calificado" ~ "homicidio",
                              delito == "homicidio_con_un_arma_mortifera" ~ "homicidio",
                              delito == "homicidio_culposo" ~ "homicidio",
                              delito == "homicidio_de_oficial_federal_o_funcionario_de_los_estados_unidos_de_america" ~ "homicidio",
                              delito == "homicidio_de_un_agente_de_la_patrulla_fronteriza" ~ "homicidio",
                              delito == "homicidio_de_un_funcionario_o_empleado_de_los_estados_unidos" ~ "homicidio",
                              delito == "homicidio_de_un_oficial_federal" ~ "homicidio",
                              delito == "homicidio_de:un_agente_de_patrulla_fronteriza" ~ "homicidio",
                              delito == "homicidio_doloso" ~ "homicidio",
                              delito == "homicidio_en_ayuda_de_la_delincuencia_organizada" ~ "homicidio",
                              delito == "homicidio_en_primer_grado" ~ "homicidio",
                              delito == "homicidio_en_primer_grado_cometido_en_una_reserva_de_nativos_estadounidenses" ~ "homicidio",
                              delito == "homicidio_en_segundo_grado" ~ "homicidio",
                              delito == "homicidio_multiple" ~ "homicidio",
                              delito == "homicidio_penal" ~ "homicidio",
                              delito == "homicidio_simple_intencional" ~ "homicidio",
                              delito == "hurto" ~ "robo",
                              delito == "importacion_y_venta_de_peces_protegidos" ~ "delito_contra_especies_protegidas",
                              delito == "incendio_intencionado" ~ "incendio",
                              delito == "incendio_provocado" ~ "incendio",
                              delito == "indecencia_con_persona_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "indecencia_con_una_persona_menor_de_edad_delitos_sexuales" ~ "delito_sexual_menores",
                              delito == "intencion_de_distribuir_mas_de_5_kg_de_cocaina_contra_la_salud" ~ "delito_contra_la_salud",
                              delito == "interferir_en_la_custodia_de_un_menor" ~ "interferir_en_proceso_judicial",
                              delito == "interferir_en_un_proceso_judicial" ~ "interferir_en_proceso_judicial",
                              delito == "invasion_a_una_casa" ~ "allanamiento_de_morada",
                              delito == "lesiones _a_una_persona_menor_de_edad" ~ "lesiones_menor_edad",
                              delito == "lesiones_a_persona_menor_de_edad" ~ "lesiones_menor_edad",
                              delito == "lesiones_a_un_conyuge" ~ "lesiones",
                              delito == "lesiones_calificadas" ~ "lesiones",
                              delito == "lesiones_calificadas_con_arma_mortifera" ~ "lesiones",
                              delito == "lesiones_con_arma_de_fuego" ~ "lesiones",
                              delito == "lesiones_con_arma_de_fuego_semiautomatica" ~ "lesiones",
                              delito == "lesiones_con_arma_mortifera" ~ "lesiones",
                              delito == "lesiones_con_la_intencion_de_cometer_una_violacion" ~ "lesiones",
                              delito == "lesiones_con_un_arma_de_fuego" ~ "lesiones",
                              delito == "lesiones_con_un_arma_de_fuego_semiautomatica" ~ "lesiones",
                              delito == "lesiones_con_un_arma_mortifera" ~ "lesiones",
                              delito == "lesiones_contra_menor_de_edad" ~ "lesiones",
                              delito == "lesiones_corporales" ~ "lesiones",
                              delito == "lesiones_corporales_graves_por_una_relacion_sexual_involuntaria_y_desviada_mediante_una_compulsion_formada" ~ "lesiones",
                              delito == "lesiones_imprudenciales" ~ "lesiones",
                              delito == "lesiones_indecentes_calificadas" ~ "lesiones",
                              delito == "lesiones_indecorosas" ~ "lesiones",
                              delito == "lesiones_mediante_el_uso_de_la_fuerza_que_probablemente_produce_heridas_corporales_graves" ~ "lesiones",
                              delito == "lesiones_que_resultan_en_un_daño_corporal_grave" ~ "lesiones",
                              delito == "lesiones_sexuales_calificadas" ~ "lesiones",
                              delito == "lesiones_simples" ~ "lesiones",
                              delito == "lesiones_y_agresion" ~ "lesiones",
                              delito == "mostrar_o_enviar_material_nocivo_para_seducir_a_persona_menor_de_edad" ~ "pornografia_infantil",
                              delito == "mutilacion_criminal_de_una_de_las_extremidades_del_cuerpo" ~ "lesiones",
                              delito == "objetos_relacionados" ~ "delito_con_arma_de_fuego",
                              delito == "obtencion_de_dinero_mediante_pretextos_falsos" ~ "robo",
                              delito == "ocasionar_discapacidad_permanente" ~ "lesiones",
                              delito == "ofensa_de_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "ofensas_de_fraude" ~ "fraude",
                              delito == "ofensas_relacionadas_con_armas" ~ "delito_con_arma_de_fuego",
                              delito == "operar_un_negocio_de_envio_de_dinero_sin_licencia" ~ "fraude",
                              delito == "otros" ~ "otros_delitos",
                              delito == "otros_delitos_relacionados" ~ "otros_delitos",
                              delito == "otros_relacionados" ~ "otros_delitos",
                              delito == "otros_relacionados_con_asuntos_migratorios" ~ "delitos_en_materia_migratoria",
                              delito == "penetracion_sexual_con_un_objeto_extraño" ~ "violacion",
                              delito == "penetracion_sexual_forzada" ~ "violacion",
                              delito == "penetracion_sexual_penal_en_primer_grado_en_que_se_implica_a_menor_de_edad" ~ "violacion_menor_de_edad",
                              delito == "poner_en_peligro_el_bienestar_de_unas_personas_menores_de_edad" ~ "poner_en_peligro_otra_persona",
                              delito == "poner_imprudentemente_en_peligro_a_otra_persona" ~ "poner_en_peligro_otra_persona",
                              delito == "por_hacer_declaraciones_falsas" ~ "falsedad_de_declaracion",
                              delito == "por_involucrarse_en_una_empresa_criminal_continuada" ~ "asociacion_delictuosa",
                              delito == "pornografía_infantil_extorsion_e_incitacion" ~ "pornografia_infantil",
                              delito == "portacion_de_un_arma_de_fuego_cargada" ~ "portacion_de_arma_de_fuego",
                              delito == "portacion_y_uso_de_armas_de_fuego" ~ "portacion_de_arma_de_fuego",
                              delito == "posesion_" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_con_armas_de_fuego_con_fines_de_trafico" ~ "trafico_de_armas",
                              delito == "posesion_criminal_de_un_arma" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_de_arma_mortifera" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_de_armas" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_de_armas_de_fuego" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_de_armas_de_fuego_por_un_expresidiario" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_de_armas_de_fuego_siendo_expresidiario" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_de_armas_para_fines_ilegales" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_de_un_arma_de_fuego_durante_la_comision_de_un_delito_grave" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_ilegal_de_armas" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_ilegal_de_armas_de_fuego" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "posesion_ilegal_de_una_arma_de_fuego" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "presentar_un_declaracion_federal_de_impuestos_falsa" ~ "falsedad_de_declaracion",
                              delito == "privacion_ilegal_de_la_libertad" ~ "secuestro",
                              delito == "produccion_de_documentos_de_identidad_legales"~ "produccion_de_documentos_de_identidad_ilegales",
                              delito == "prostitucion" ~ "explotacion_sexual",
                              delito == "prostitucion_interestatal" ~ "explotacion_sexual",
                              delito == "prostitucion_o_chantaje" ~ "explotacion_sexual",
                              delito == "provocar_un_incendio" ~ "incendio",
                              delito == "rapto" ~ "secuestro",
                              delito == "recibir_objetos_robados" ~ "robo",
                              delito == "relacion_sexual_involuntaria_y_desviada" ~ "violacion",
                              delito == "relacion_sexual_involuntaria_y_desviada_con_una_persona_menor_de_edad" ~ "violacion_menor_de_edad",
                              delito == "relaciones_sexuales_o_sodomia" ~ "violacion",
                              delito == "robo" ~ "robo",
                              delito == "robo_a_habitacion" ~ "robo",
                              delito == "robo_armado" ~ "robo",
                              delito == "robo_armado_con_violencia" ~ "robo",
                              delito == "robo_bancario" ~ "robo",
                              delito == "robo_calificado" ~ "robo",
                              delito == "robo_con_violencia" ~ "robo",
                              delito == "robo_con_violencia_calificado" ~ "robo",
                              delito == "robo_con_violencia_de_un_vehiculo" ~ "robo",
                              delito == "robo_con_violencia_en_segundo_grado" ~ "robo",
                              delito == "robo_de_automovil" ~ "robo",
                              delito == "robo_de_fondos_bancarios" ~ "robo",
                              delito == "robo_de_identidad" ~ "robo",
                              delito == "robo_de_identidad_calificado" ~ "robo",
                              delito == "robo_de_propiedad_gubernamental" ~ "robo",
                              delito == "homicidio" ~ "homicidio",
                              delito == "lesiones" ~ "lesiones",
                              delito == "secuestro" ~ "secuestro",
                              delito == "violacion" ~ "violacion",
                              delito == "delitos_sexuales" ~ "delitos_sexuales",
                              delito == "asociacion_delictuosa" ~ "asociacion_delictuosa",
                              delito == "contra_la_salud" ~ "delito_contra_la_salud",
                              delito == "secuestro_internacional_de_sus_propias_hijas" ~ "secuestro",
                              delito == "tentativa_de_homicidio" ~ "homicidio",
                              delito == "asalto_sexual" ~ "asalto_sexual",
                              delito == "delitos_sexuales_contra_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "lavado_de_dinero" ~ "lavado_de_dinero",
                              delito == "delincuencia_organizada" ~ "delincuencia_organizada",
                              delito == "allanamiento_de_morada_a_casa_habitacion_en_primer_grado" ~ "allanamiento_de_morada",
                              delito == "violacion_forzada_de_copula_oral" ~ "violacion",
                              delito == "penetracion_sexual_con_un_objeto_extrano" ~ "violacion",
                              delito == "allanamiento_de_morada" ~ "allanamiento_de_morada",
                              delito == "homicido" ~ "homicidio",
                              delito == "abuso_infantil" ~ "abuso_sexual_menores",
                              delito == "uso_de_armas" ~ "delito_con_arma_de_fuego",
                              delito == "falsificacion" ~ "falsificacion",
                              delito == "traficar_con_la_identificacion_de_otra_persona_o_entidad" ~ "falsificacion",
                              delito == "secuestro_calificado" ~ "secuestro",
                              delito == "confinamiento_ilicito" ~ "secuestro",
                              delito == "fraude" ~ "fraude",
                              delito == "trafico_de_personas" ~ "trafico_de_personas",
                              delito == "sodomia" ~ "delito_sexual",
                              delito == "trafico_con_la_identidad_de_otra_persona_o_entidad" ~ "falsificacion",
                              delito == "tentativa_de_robo_armado" ~ "robo",
                              delito == "uso_ilicito_de_arma_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "amenazas" ~ "amenazas",
                              delito == "contrabando" ~ "contrabando",
                              delito == "corrupcion_por_parte_de_servidores_publicos" ~ "corrupcion",
                              delito == "obstruccion_de_la_justicia" ~ "obstruccion_de_la_justicia",
                              delito == "intimidacion" ~ "intimidacion",
                              delito == "tentativa_de_robo_con_violencia" ~ "robo",
                              delito == "trafico_de_personas_que_resulta_en_muerte" ~ "trafico_de_personas",
                              delito == "uso_de_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "acceso_ilicito_a_sistemas_informatica" ~ "acceso_ilicito_a_sistemas_informatica",
                              delito == "pornografia_infantil" ~ "pornografia_infantil",
                              delito == "robo_de_vehiculos" ~ "robo",
                              delito == "evasion_de_arresto" ~ "evasion_de_arresto",
                              delito == "tentativa_de_lesiones_con_arma_de_fuego" ~ "lesiones",
                              delito == "trata_de_personas_con_fines_de_explotacion_sexual" ~ "trata_de_personas",
                              delito == "transportar_a_persona_menor_de_edad_con_fines_de_prostitucion" ~ "explotacion_sexual",
                              delito == "transportar_personas_indocumentadas_para_obtener_ganancia_economica" ~ "trafico_de_personas",
                              delito == "violacion_cinco_mujeres_de_la_tercera_edad" ~ "violacion",
                              delito == "robo_de_vehiculos" ~ "robo",
                              delito == "malversacion_de_fondos" ~ "corrupcion",
                              delito == "terrorismo_callejero" ~ "terrorismo",
                              delito == "poner_en_peligro_la_vida_de_una_persona" ~ "poner_en_peligro_otra_persona",
                              delito == "portacion_de_arma_de_fuego" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "delitos_cometidos_contra_la_administracion_federal_de_medicamentos" ~ "delitos_cometidos_contra_la_administracion_federal_de_medicamentos",
                              delito == "venta_de_armas_de_fuego" ~ "trafico_de_armas",
                              delito == "extorsion" ~ "extorsion",
                              delito == "posesion_ilegal_de_arma_de_fuego" ~ "posesion_ilegal_de_arma_de_fuego",
                              delito == "alteracion_de_pruebas" ~ "alteracion_de_pruebas",
                              delito == "prender_fuego_abordo_de_una_aeronave" ~ "incendio",
                              delito == "uso_de_arma_de_fuego"~ "delito_con_arma_de_fuego",
                              delito == "tentativa_de_lavado_de_dinero"~ "lavado_de_dinero",
                              delito == "tentativa_de_violacion" ~ "violacion",
                              delito == "abuso_sexual" ~ "abuso_sexual",
                              delito == "violacion_equiparada" ~ "violacion",
                              delito == "corrupcion_de_menores" ~ "corrupcion_de_menores",
                              delito == "trafico_de_indocumentados" ~ "trafico_de_personas",
                              delito == "asesinato" ~ "homicidio",
                              delito == "ataque" ~ "ataque",
                              delito == "violacion_calificada" ~ "violacion",
                              delito == "tentativa_de_lavado_de_dinero" ~ "lavado_de_dinero",
                              delito == "transportar_recibir_poseer_pornografia_infantil" ~ "pornografia_infantil",
                              delito == "transportar_indocumentados" ~ "trafico_de_personas",
                              delito == "negligencia_infantil" ~ "abuso_infantil",
                              delito == "asalto_sexual_calificado_como_violacion" ~ "violacion",
                              delito == "violacion_forzada" ~ "violacion",
                              delito == "construccion_financiamiento_y_uso_de_un_tunel_que_cruza_una_frontera_internacional" ~ "construccion_financiamiento_y_uso_de_un_tunel_que_cruza_una_frontera_internacional",
                              delito == "abuso_infantil_que_resulta_en_muerte"~ "abuso_sexual_menores",
                              delito == "otros_delitos" ~ "otros_delitos",
                              delito ==  "viajar_interestatalmente_para_comercio_interestatal_con_la_intencion_de_promover_la_actividad_ilegal_posesion_y_distribucion_de_marihuana" ~ "delito_contra_la_salud",
                              delito == "penetracion_sexual_forzada" ~ "violacion",
                              delito == "copula_oral_forzada" ~ "violacion",
                              delito == "sodomia_calificada" ~ "delito_sexual",
                              delito == "violencia_sexual_calificada" ~ "delito_sexual",
                              delito == "crueldad_contra_personas_menor_de_edad" ~ "abuso_sexual_menores",
                              delito == "tener_un_arma_en_un_vehiculo_sin_ser_el_propietario_registrado_de_esa_arma_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "sodomia_con_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "robo_de_vehiculo" ~ "robo",
                              delito == "transportar_menor_de_edad_en_comercio_extranjero_con_el_fin_de_cometer_delitos_sexuales" ~ "trata_de_personas",
                              delito == "viajar_en_comercio_extranjero_con_el_fin_de_involucrarse_sexualmente_con_menor_de_edad" ~ "explotacion_sexual",
                              delito == "tentativa_de_robo" ~ "robo",
                              delito == "soborno" ~ "corrupcion",
                              delito == "violacion_en_primer_grado" ~ "violacion",
                              delito == "sodomia_con_personas_menores_de_edad" ~ "delito_sexual_menores",
                              delito == "copula_oral_forzada" ~ "violacion",
                              delito == "secuestro_para_cometer_un_delito_sexual" ~ "secuestro",
                              delito == "acto_lacsivo_y_lujurioso_con_menor_de_edad" ~ "abuso_sexual_menores",
                              delito == "trafico_de_personas_y_otros" ~ "trafico_de_personas",
                              delito == "sometimiento_ilegal" ~ "sometimiento_ilegal",
                              delito == "tentativa_de_homicidio_a_un_oficial" ~ "homicidio",
                              delito == "cargos_relacionados_con_armas" ~ "delito_con_arma_de_fuego",
                              delito == "transporte_ilegal_de_desechos_peligrosos" ~ "transporte_ilegal_de_desechos_peligrosos",
                              delito == "disposicion_ilegal_de_desechos_peligrosos" ~ "disposicion_ilegal_de_desechos_peligrosos",
                              delito == "transporte_de_desechos_peligrosos_sin_un_manifiesto" ~ "transporte_ilegal_de_desechos_peligrosos",
                              delito == "violacion_a_menor_de_edad" ~ "violacion_menor_de_edad",
                              delito == "tentativa_de_secuestro" ~ "secuestro",
                              delito == "trafico_de_armas_de_fuego" ~ "trafico_de_armas",
                              delito == "lesiones_con_armas_de_fuego" ~ "lesiones",
                              delito == "tentativa_de_allanamiento_de_morada" ~ "allanamiento_de_morada",
                              delito == "usar_portar_bladir_y_descargar_un_arma_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "trafico_de_personas_con_fines_de_explotacion_sexual" ~ "trata_de_personas",
                              delito == "cometer_actos_lujuriosos_o_lascivos_con_persona_menor_de_edad_sexuales" ~ "delito_sexual_menores",
                              delito == "filiacion_a_una_pandilla" ~ "asociacion_delictuosa",
                              delito == "uso_ilegal_de_una_instalacion_de_comunicaciones" ~ "uso_ilegal_instalacion_de_comunicaciones",
                              delito == "tentativa_de_homicidio_de_un_oficial_de_paz" ~ "homicidio",
                              delito == "robo_con_violencia_en_segundo_grado" ~ "robo",
                              delito == "robo_o_uso_no_autorizado_de_un_vehiculo_hurto" ~ "robo",
                              delito == "tentativa_de_allanamiento_de_un_vehiculo_que_estaba_cerrado_con_llave" ~ "robo",
                              delito == "violacion_de_persona_menor_de_edad" ~ "violacion_menor_de_edad",
                              delito == "trafico" ~ "trafico_de_armas",
                              delito == "tentativa_exportar_vender_y_transportar_mercancia" ~ "trafico_de_armas",
                              delito == "tortura" ~ "tortura",
                              delito == "violacion_con_un_objeto_mediante_el_uso_de_la_fuerza" ~ "violacion",
                              delito == "violencia" ~ "violencia",
                              delito == "coaccion" ~ "coaccion",
                              delito == "trafico_de_armas" ~ "trafico_de_armas",
                              delito == "trafico_de_armas_de_fuego" ~ "trafico_de_armas",
                              delito == "trata_de_indocumentados" ~ "trafico_de_personas",
                              delito == "tentativa de homicidio" ~ "homicidio",
                              delito == "homicidio_contratado" ~ "homicidio",
                              delito == "violacion_de_una_persona_menor_de_edad" ~"violacion_menor_de_edad",
                              delito == "secuestro_parental_internacional" ~ "secuestro",
                              delito == "delito_con_armas_de_fuego" ~ "delito_con_arma_de_fuego",
                              delito == "trafico_de_personas_con_fines_de_explotacion_sexual" ~ "trata_de_personas",
                              delito == "trata_de_personas" ~ "trata_de_personas",
                              delito == "trata_de_indocumentados" ~ "trafico_de_personas",
                              delito == "albergue_a_indocumentados" ~ "albergue_a_indocumentados",
                              delito == "chantaje" ~ "chantaje",
                              delito == "acecho_interestatal" ~ "acecho_interestatal",
                              delito == "crimen_organizado" ~ "delincuencia_organizada",
                              delito == "asocicion_delictuosa" ~ "asociacion_delictuosa",
                              delito == "secuestro_para_cometer_un_robo_de_auto_con_violencia" ~ "secuestro",
                              delito == "tentativa_de_homicidio_premeditado_deliberado_e_intencional" ~ "homicidio",
                              delito == "abuso_de_una_persona_menor_de_edad" ~ "abuso_sexual_menores",
                              delito == "produccion_de_documentos_de_identidad_ilegales" ~ "falsificacion",
                              delito == "transferencia_de_un_material_obseno_a_una_persona_menor_de_edad" ~ "delito_sexual_menores",
                              delito == "secuestro_en_segundo_grado" ~ "secuestro",
                              delito == "posesion_ilegal_de_una_sustancia_controlada" ~ "delito_contra_la_salud",
                              delito == "desnutricion" ~ "desnutricion",
                              delito == "tomar_y_conducir_de_forma_ilegal_un_automovil" ~ "conducir_bajo_el_influjo_de_alcohol",
                              delito == "transporte_de_persona_menor_de_edad_para_fines_de_prostitucion" ~ "trata_de_personas",
                              delito == "transporte_de_personas_para_fines_de_prostitucion"~ "trata_de_personas",
                              delito == "tentativa_de_homicidio_en_primer_grado" ~ "homicidio",
                              delito == "uso_de_arma_mortifera" ~ "delito_con_arma_de_fuego",
                              delito == "delitos_aduanales" ~ "delitos_aduanales",
                              delito == "viajar_en_un_comercio_interestatal" ~ "trafico_de_personas",
                              delito == "usar_el_correo_e_instalaciones_de_cualquier_comercio_interestatal_con_la_intencion_de_distribuir_las_ganancias_de_cualquier_actividad_ilegal_asi_como_promover_administrar_realizar_o_facilitar_la_promocion_administracion_creacion_o_realizacion_de_cualqueir_actividad_ilegal" ~ "otros_delitos",
                              delito == "violacion_sexual_forzada" ~ "violacion",
                              delito == "usar_y_poseer_un_arma_de_fuego_en_fomento_de_un_delito_violento" ~ "delito_con_arma_de_fuego",
                              delito == "sodomia_criminal" ~ "delitos_sexuales",
                              delito == "conducir_bajo_el _influjo_de_alcohol" ~ "conducir_bajo_el_influjo_de_alcohol",
                              delito == "conducta_sexual_con_menor" ~ "agresion_sexual_contra_menor",
                              delito == "delito_sexual_menores" ~ "delito_sexual_contra_menores",
                              TRUE ~ delito),
           fecha_peticion = dmy(fecha_peticion),
           fecha_resolucion = dmy(fecha_resolucion),
           tiempo_resolucion = as.duration(fecha_resolucion-fecha_peticion),
           fecha_peticion2 = fecha_peticion) %>%
    separate(fecha_peticion2, into = c("ano_peticion", "mes_peticion", "dia_peticion"))
           # ano = substring(fecha_peticion,-2))
# extradiciones_2 %>% select(tiempo_resolucion)  %>% na.exclude()
#     %>% mean()

#
#
#     mutate(delito = as_factor(delito))
#
# tabyl(extradiciones$delito)
